pipeline: 
  build: 
    image: docker:1.12-dind
    commands:
      - echo 'build ok'

  notify:
    image: plugins/slack 
    webhook_url: $SLACK_URL
    channel: general
    template: >
      Build #{{ build.number }} finished with a {{ build.status }} status. {{ build.user }} / {{ build }}
    when:
      status: [ success, failure ]
